Replace counter code

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -32,10 +32,9 @@ jobs:
     - name: Run container and wait until healthy
       run: |
         docker run -t --name container-under-test gluwa/container-under-test tail > /dev/null &
-        sleep 15
         COUNT=0
-        while [ "`docker inspect -f {{.State.Health.Status}} container-under-test`" != "healthy" ] && [ $COUNT -lt 20 ]; do let "COUNT++"; echo "Checking health status - Attempt $COUNT of 20"; sleep 15; done
-        if [ $COUNT -ge 20 ]; then exit 1; fi
+        while [ "`docker inspect -f {{.State.Health.Status}} container-under-test`" != "healthy" ] && [ $COUNT -lt 20 ]; do COUNT=$((COUNT+1)); echo "Checking health status - Attempt $COUNT of 20"; sleep 15; done
+        if [ $COUNT -ge 20 ]; then echo "Error - Failed to verify healthcheck after 5 minutes"; exit 1; else echo "Successfully verified healthcheck!"; fi
 
     - name: Kill and remove container
       run: |
